-- Wipe player accounts. NPC shards live in code, not these tables.
delete from season_claims;
delete from season_results;
delete from shard_members;
delete from gem_grants;
delete from game_saves;
delete from staff;
delete from duels;
delete from clan_members;
delete from clans;
delete from inventories;
delete from trades;
delete from world_chat;
delete from push_subscriptions;
delete from crusaders;
delete from "session";
delete from "account";
delete from "verification";
delete from "user";
