/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ApiAuthReadyRouteImport } from './routes/api/auth-ready'
import { Route as ApiBgRouteImport } from './routes/api/bg'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthReadyRoute = ApiAuthReadyRouteImport.update({
  id: '/api/auth-ready',
  path: '/api/auth-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBgRoute = ApiBgRouteImport.update({
  id: '/api/bg',
  path: '/api/bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copyright': typeof CopyrightRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/auth-ready': typeof ApiAuthReadyRoute
  '/api/bg': typeof ApiBgRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copyright': typeof CopyrightRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/auth-ready': typeof ApiAuthReadyRoute
  '/api/bg': typeof ApiBgRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copyright': typeof CopyrightRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/api/auth-ready': typeof ApiAuthReadyRoute
  '/api/bg': typeof ApiBgRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copyright'
    | '/guide'
    | '/login'
    | '/privacy'
    | '/support'
    | '/api/auth-ready'
    | '/api/bg'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copyright'
    | '/guide'
    | '/login'
    | '/privacy'
    | '/support'
    | '/api/auth-ready'
    | '/api/bg'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/copyright'
    | '/guide'
    | '/login'
    | '/privacy'
    | '/support'
    | '/api/auth-ready'
    | '/api/bg'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopyrightRoute: typeof CopyrightRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  ApiAuthReadyRoute: typeof ApiAuthReadyRoute
  ApiBgRoute: typeof ApiBgRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-ready': {
      id: '/api/auth-ready'
      path: '/api/auth-ready'
      fullPath: '/api/auth-ready'
      preLoaderRoute: typeof ApiAuthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bg': {
      id: '/api/bg'
      path: '/api/bg'
      fullPath: '/api/bg'
      preLoaderRoute: typeof ApiBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopyrightRoute: CopyrightRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  ApiAuthReadyRoute: ApiAuthReadyRoute,
  ApiBgRoute: ApiBgRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
